// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf5MnCOTBayQfipBik4f_FZ9m7XdwumUY',
    appId: '1:157289010810:web:a9992c85177608f7988dc3',
    messagingSenderId: '157289010810',
    projectId: 'chatapp-2119e',
    authDomain: 'chatapp-2119e.firebaseapp.com',
    storageBucket: 'chatapp-2119e.appspot.com',
    measurementId: 'G-SWYH9H1HLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKaBaukaKzdpWc8Xi9-ZOLbW6YEwpjzwM',
    appId: '1:157289010810:android:b04eb1604061f4b2988dc3',
    messagingSenderId: '157289010810',
    projectId: 'chatapp-2119e',
    storageBucket: 'chatapp-2119e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPPVDR2gPTnQlMd8PDCx76msJWjbLOt8',
    appId: '1:157289010810:ios:f941d770b1d673b2988dc3',
    messagingSenderId: '157289010810',
    projectId: 'chatapp-2119e',
    storageBucket: 'chatapp-2119e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPPVDR2gPTnQlMd8PDCx76msJWjbLOt8',
    appId: '1:157289010810:ios:f941d770b1d673b2988dc3',
    messagingSenderId: '157289010810',
    projectId: 'chatapp-2119e',
    storageBucket: 'chatapp-2119e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf5MnCOTBayQfipBik4f_FZ9m7XdwumUY',
    appId: '1:157289010810:web:ebf15d488658bf70988dc3',
    messagingSenderId: '157289010810',
    projectId: 'chatapp-2119e',
    authDomain: 'chatapp-2119e.firebaseapp.com',
    storageBucket: 'chatapp-2119e.appspot.com',
    measurementId: 'G-ZYQVKV5QZ4',
  );
}
